module.exports = {
  outputDir: require("path").resolve(__dirname, "../backend/src/public"),
  assetsDir: "spa",
  productionSourceMap: false, // Setting this to false can speed up production builds if you don't need source maps for production.
  filenameHashing: false, // By default, generated static assets contains hashes in their filenames for better caching control. However, this requires the index HTML to be auto-generated by Vue CLI. If you cannot make use of the index HTML generated by Vue CLI, you can disable filename hashing by setting this option to false.
  /* configureWebpack: { // Bundle .js files into less files as possible
    optimization: {
      splitChunks: true
    }
  } */
}
